language: python
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+$/"
matrix:
  fast_finish: true
  include:
  - os: linux
    name: Linux
    dist: bionic
    python:
    - 3.6
    - 3.7
    env:
    - BUILD_TARGET=linux
    addons:
      apt:
        packages:
        - patchelf
  - os: osx
    name: macOS
    osx_image: xcode11.2
    python:
    - 3.7
    env:
    - BUILD_TARGET=macos
  - os: windows
    name: windows
    python:
    - 3.6
    - 3.7
    env:
    - BUILD_TARGET=windows
install:
- set -e
- pip install -r requirements.txt -r requirements-dev.txt
- if [[ "${BUILD_TARGET}" = "linux" ]]; then
    pip install auditwheel; fi
script:
- set -e
- python --version
- pip --version
- if [[ "${BUILD_TARGET}" = "linux" ]]; then
    python setup.py bdist_wheel;
    auditwheel
    repair dist/*.whl;
  fi
deploy:
- provider: pypi
  on:
    tags: true
  file_glob: true
  file: "wheelhouse/*.whl"
  user: "__token__"
  password:
    secure: CiOtzgly9Rl0KwaA3W3FJTzSaUoSpRVPgSRj+x9UdmDBKHm9dvW3kc5amsUKzx7jF9qb2Cuyw2Bg9kmq7SIIqvvN14/3NkzTb2aDpE+f/O627asKJlrr5CuQtmwFX//ZjLIeLFPySBj/Oz1SUz39hqtRVkyTAPfvxiVu52AQveXqyxhcgC5ALI/kIAVaWeKBqH8f6PJ5HUphL2u+QOO1/r88tEumbmVUA6tvQZxHUsu7tU1SOwB4SAfCwTfwJ8h0ZUEicuTkUB3KJc6gDWF8i2AUi1akrysAO4DDd606K1APA7QusTq+PP16tG23ul6kmme8SNRXZUouqGv902giif3TZdJqSyoPkih4TTUUeQ47xBQ81EJba5lXbEZIu4N3Soxl6RSa6O85LNuc9XKxNSEbruRWROxg+hMBh+8403S4NlWfxnri4SwM8iM98psWjTGyl/JLLNU7JJniiuBY5coEV65XzP/6gnAdo1TGy3kdolnTeocT1Nrx0WSH8LxZM6LhWdt2uV1eJK4NT2MhxW8CI/S6BGiwZV/31+HfMUoseEjYPPaGFDazIWtC6WWlPRFLsk1cktNjK+/KxDThkVBW+kkiGrqifRi8u+TNjWLRJbotNnDq5RYipvXjCIurl1UlPIDx6l7JnJjknblu35JjjOevOn/WDIJdpDTODdw=
