language: python
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+$/"
matrix:
  fast_finish: true
  include:
  - os: linux
    name: Linux
    dist: bionic
    python:
    - 3.6
    - 3.7
    before_install:
      python3 --version;
      pip3 --version;
    env:
    - BUILD_TARGET=linux
    - PYTHON_BIN=python3
    addons:
      apt:
        packages:
        - patchelf
  - os: osx
    name: macOS
    osx_image: xcode11.2
    language: shell # python not working
    before_install:
      python3 --version;
      pip3 --version;
    env:
    - BUILD_TARGET=macos
    - PYTHON_BIN=python3
  - os: windows
    language: shell # python not supported yet
    name: windows
    before_install:
      choco install python3 --version=3.7.5;
      python -m pip install --upgrade pip;
      python --version;
      pip3 --version;
    env:
    - BUILD_TARGET=windows
    - PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - PYTHON_BIN=python
install:
- set -e
- pip3 install -r requirements.txt -r requirements-dev.txt
- pip3 install auditwheel
script:
- set -e
- $PYTHON_BIN setup.py bdist_wheel
- if [[ "${BUILD_TARGET}" = "linux" ]]; then
    auditwheel repair dist/*.whl;
  fi
- if [[ "${BUILD_TARGET}" = "windows" ]]; then
    mkdir wheelhouse;
    ls dist/*any.whl | sed -e 'p;s/any/win32/' | xargs -n2 cp;
    ls dist/*any.whl | sed -e 'p;s/any/win_amd64/' | xargs -n2 cp;
    mv dist/*win32.whl dist/*win_amd64.whl wheelhouse/;
  fi
deploy:
- provider: pypi
  on:
    tags: true
  file_glob: true
  file: "wheelhouse/*.whl"
  user: "__token__"
  password:
    secure: CiOtzgly9Rl0KwaA3W3FJTzSaUoSpRVPgSRj+x9UdmDBKHm9dvW3kc5amsUKzx7jF9qb2Cuyw2Bg9kmq7SIIqvvN14/3NkzTb2aDpE+f/O627asKJlrr5CuQtmwFX//ZjLIeLFPySBj/Oz1SUz39hqtRVkyTAPfvxiVu52AQveXqyxhcgC5ALI/kIAVaWeKBqH8f6PJ5HUphL2u+QOO1/r88tEumbmVUA6tvQZxHUsu7tU1SOwB4SAfCwTfwJ8h0ZUEicuTkUB3KJc6gDWF8i2AUi1akrysAO4DDd606K1APA7QusTq+PP16tG23ul6kmme8SNRXZUouqGv902giif3TZdJqSyoPkih4TTUUeQ47xBQ81EJba5lXbEZIu4N3Soxl6RSa6O85LNuc9XKxNSEbruRWROxg+hMBh+8403S4NlWfxnri4SwM8iM98psWjTGyl/JLLNU7JJniiuBY5coEV65XzP/6gnAdo1TGy3kdolnTeocT1Nrx0WSH8LxZM6LhWdt2uV1eJK4NT2MhxW8CI/S6BGiwZV/31+HfMUoseEjYPPaGFDazIWtC6WWlPRFLsk1cktNjK+/KxDThkVBW+kkiGrqifRi8u+TNjWLRJbotNnDq5RYipvXjCIurl1UlPIDx6l7JnJjknblu35JjjOevOn/WDIJdpDTODdw=
