# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: striker/striker.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'striker/striker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import mavsdk_options_pb2 as mavsdk__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15striker/striker.proto\x12\x12mavsdk.rpc.striker\x1a\x14mavsdk_options.proto\"\x1b\n\x19SubscribeHeartbeatRequest\"E\n\x11HeartbeatResponse\x12\x30\n\theartbeat\x18\x01 \x01(\x0b\x32\x1d.mavsdk.rpc.striker.Heartbeat\"\x1b\n\x19SubscribeSysStatusRequest\"F\n\x11SysStatusResponse\x12\x31\n\nsys_status\x18\x01 \x01(\x0b\x32\x1d.mavsdk.rpc.striker.SysStatus\"\x84\x01\n\tHeartbeat\x12\x13\n\x0b\x63ustom_mode\x18\x01 \x01(\r\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\x11\n\tautopilot\x18\x03 \x01(\r\x12\x11\n\tbase_mode\x18\x04 \x01(\r\x12\x15\n\rsystem_status\x18\x05 \x01(\r\x12\x17\n\x0fmavlink_version\x18\x06 \x01(\r\"\xfe\x03\n\tSysStatus\x12\'\n\x1fonboard_control_sensors_present\x18\x01 \x01(\r\x12\'\n\x1fonboard_control_sensors_enabled\x18\x02 \x01(\r\x12&\n\x1eonboard_control_sensors_health\x18\x03 \x01(\r\x12\x0c\n\x04load\x18\x04 \x01(\r\x12\x17\n\x0fvoltage_battery\x18\x05 \x01(\r\x12\x17\n\x0f\x63urrent_battery\x18\x06 \x01(\x05\x12\x16\n\x0e\x64rop_rate_comm\x18\x07 \x01(\r\x12\x13\n\x0b\x65rrors_comm\x18\x08 \x01(\r\x12\x15\n\rerrors_count1\x18\t \x01(\r\x12\x15\n\rerrors_count2\x18\n \x01(\r\x12\x15\n\rerrors_count3\x18\x0b \x01(\r\x12\x15\n\rerrors_count4\x18\x0c \x01(\r\x12\x19\n\x11\x62\x61ttery_remaining\x18\r \x01(\x05\x12\x30\n(onboard_control_sensors_present_extended\x18\x0e \x01(\r\x12\x30\n(onboard_control_sensors_enabled_extended\x18\x0f \x01(\r\x12/\n\'onboard_control_sensors_health_extended\x18\x10 \x01(\r2\xf0\x01\n\x0eStrikerService\x12n\n\x12SubscribeHeartbeat\x12-.mavsdk.rpc.striker.SubscribeHeartbeatRequest\x1a%.mavsdk.rpc.striker.HeartbeatResponse\"\x00\x30\x01\x12n\n\x12SubscribeSysStatus\x12-.mavsdk.rpc.striker.SubscribeSysStatusRequest\x1a%.mavsdk.rpc.striker.SysStatusResponse\"\x00\x30\x01\x42!\n\x11io.mavsdk.strikerB\x0cStrikerProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'striker.striker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021io.mavsdk.strikerB\014StrikerProto'
  _globals['_SUBSCRIBEHEARTBEATREQUEST']._serialized_start=67
  _globals['_SUBSCRIBEHEARTBEATREQUEST']._serialized_end=94
  _globals['_HEARTBEATRESPONSE']._serialized_start=96
  _globals['_HEARTBEATRESPONSE']._serialized_end=165
  _globals['_SUBSCRIBESYSSTATUSREQUEST']._serialized_start=167
  _globals['_SUBSCRIBESYSSTATUSREQUEST']._serialized_end=194
  _globals['_SYSSTATUSRESPONSE']._serialized_start=196
  _globals['_SYSSTATUSRESPONSE']._serialized_end=266
  _globals['_HEARTBEAT']._serialized_start=269
  _globals['_HEARTBEAT']._serialized_end=401
  _globals['_SYSSTATUS']._serialized_start=404
  _globals['_SYSSTATUS']._serialized_end=914
  _globals['_STRIKERSERVICE']._serialized_start=917
  _globals['_STRIKERSERVICE']._serialized_end=1157
# @@protoc_insertion_point(module_scope)
